# Generated by Django 6.0.2 on 2026-02-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SCADAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locno', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('outdoor_temp', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('nacelle_pos', models.FloatField()),
                ('active_power', models.FloatField()),
                ('frequency', models.FloatField()),
            ],
            options={
                'db_table': 'scada_data',
                'indexes': [models.Index(fields=['datetime', 'locno'], name='scada_data_datetim_c56b44_idx')],
            },
        ),
    ]
