# Generated by Django 6.0.2 on 2026-02-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scadadata',
            unique_together={('datetime', 'locno')},
        ),
    ]
