# Generated by Django 6.0.2 on 2026-02-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_alter_scadadata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scadadata',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scadadata',
            constraint=models.UniqueConstraint(fields=('datetime', 'locno'), name='unique_datetime_locno'),
        ),
    ]
