# Generated by Django 6.0.2 on 2026-02-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_alter_scadadata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScadaDataEnercon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('asset_name', models.CharField(max_length=100)),
                ('active_power_generation', models.FloatField(blank=True, null=True)),
                ('wind_direction_outside_nacelle', models.FloatField(blank=True, null=True)),
                ('wind_speed_outside_nacelle', models.FloatField(blank=True, null=True)),
                ('temperature_outside_nacelle', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scada_data_enercon',
                'managed': False,
            },
        ),
    ]
