# Generated by Django 6.0.2 on 2026-02-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_scadadataenercon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTMW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('misalignment_percent', models.FloatField(blank=True, null=True)),
                ('avg_active_power', models.FloatField(blank=True, null=True)),
                ('avg_ambient_temperature', models.FloatField(blank=True, null=True)),
                ('avg_wind_speed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gtmw',
                'indexes': [models.Index(fields=['device', 'date'], name='gtmw_device_9805c3_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
