# Generated by Django 6.0.2 on 2026-02-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0005_gtmw'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhouseSCADAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('asset_name', models.CharField(max_length=50)),
                ('active_power_generation', models.FloatField(blank=True, null=True)),
                ('windspeed_outside_nacelle', models.FloatField(blank=True, null=True)),
                ('temperature_outside_nacelle', models.FloatField(blank=True, null=True)),
                ('winddirection_outside_nacelle', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inhouse_scada_data',
                'indexes': [models.Index(fields=['timestamp'], name='inhouse_sca_timesta_84833f_idx'), models.Index(fields=['asset_name'], name='inhouse_sca_asset_n_786acd_idx')],
                'unique_together': {('timestamp', 'asset_name')},
            },
        ),
    ]
